apiVersion: v1
kind: Service
metadata:
  name: monolith-application
  namespace: monolith
spec:
  type: LoadBalancer
  selector:
    app: monolith-application
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
